New diffs for OpenPli

diff --git a/root/release/rcS_neutrino_spark7162 b/root/release/rcS_neutrino_spark7162
--- a/root/release/rcS_neutrino_spark7162
+++ b/root/release/rcS_neutrino_spark7162
@@ -1,15 +1,33 @@
 #!/bin/sh
+#Version 150404.1
+
+echo "Spark 7162"
 
 MODDIR=/lib/modules
-echo "init frontpanel"
-insmod $MODDIR/aotom.ko
+
+echo "Init frontpanel"
+insmod $MODDIR/aotom.ko paramDebug=0
 insmod $MODDIR/simu_button.ko
+if [ -e $MODDIR/encrypt.ko ]; then
+   insmod $MODDIR/encrypt.ko
+fi
+
+#clockon=`cat /etc/enigma2/settings | grep systemoptions.clockon | cut -d "=" -f2`
+#if [ ! $clockon ]; then
+#   /bin/fp_control -tm 1
+#else
+#   /bin/fp_control -tm 0
+#fi
 
 if [ -e /var/etc/.firstboot ]; then
-   echo "WAIT 1 min" >/dev/vfd
+   echo "Wait 1 min." > /dev/vfd
    echo "WAIT 1 min"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   echo "Load 10" > /dev/vfd
+   echo "LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
@@ -17,145 +35,308 @@ fi
 
 insmod $MODDIR/e2_proc.ko
 
+/etc/init.d/autofs start
 
-if [ ! -e /var/etc/.firstboot ]; then
+if [ -e "$MODDIR/cpu_frequ.ko" ]; then
+   insmod $MODDIR/cpu_frequ.ko
+   cpufreq=`cat /etc/enigma2/settings | grep systemoptions.freq | cut -d "=" -f2`
+   case $cpufreq in
+      200) overclk=5123;;
+      300) overclk=2561;;
+      450) overclk=3841;;
+      500) overclk=12803;;
+      540) overclk=4609;;
+      600) overclk=5121;;
+      630) overclk=5377;;
+      650) overclk=16643;;
+      700) overclk=17923;;
+      710) overclk=18179;;
+      750) overclk=19203;;
+      775) overclk=39686;;
+      800) overclk=20483;;
+      *)   cpufreq=540
+           overclk=4609;;
+   esac
+   echo $overclk > /proc/cpu_frequ/pll0_ndiv_mdiv
+   echo "Setting CPU clock speed to $cpufreq MHz (overclk=$overclk)"
+fi
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
+echo "Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
-#   echo "starting telnetd"
-#   /usr/sbin/telnetd -l /bin/autologin
+echo -n "Starting telnetd "
+autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
+if [ ! $autologin ]; then
+   /usr/sbin/telnetd -l /bin/autologin
+   echo "with autologin"
+else
+   /usr/sbin/telnetd -l /bin/login
+   echo "with normal login"
+fi
 
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-sti7105.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv
+#clockon=`cat /etc/enigma2/settings | grep systemoptions.clockon | cut -d "=" -f2`
+#if [ ! $clockon ]; then
+#   /bin/fp_control -tm 1
+#else
+   /bin/fp_control -tm 0
+#fi
 
-   echo "LOADING MODULES"
-   echo "LOAD" > /dev/vfd
+echo "Init stmfb (LOAD 9)"
+echo "Load 9" > /dev/vfd
+insmod $MODDIR/stmcore-display-sti7105.ko
 
-   if [ ! -e /lib/firmware/audio.elf ]; then
-      echo "FW MISSING!!!"
-   fi
+if  grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
+  insmod $MODDIR/stmfb.ko display0=720x576i-32@50:15m:pal:rgb:rgb; #SCART
+else
+  insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:rgb:rgb; #HDMI
+fi
 
-   echo "load video firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
-#   /bin/stslave -t st231.0 -R /lib/firmware/video.elf
-   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf
+echo "Loading modules"
 
-   echo "load audio firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
-#   /bin/stslave -t st231.1 -R /lib/firmware/audio.elf
-   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
+if [ ! -e /boot/audio.elf ]; then
+   echo "NO AUDIO FW!!!"
+   echo "NO AUDIO FW!!!" > /dev/vfd
+fi
 
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
-   insmod $MODDIR/mme_host.ko transport0=shm
+echo "Load audio firmware (LOAD 8)"
+echo "Load 8" > /dev/vfd
+dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
+if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
+   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
+else
+   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
+fi
 
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=avs_none
+echo "Load video firmware (LOAD 7)"
+echo "Load 7" > /dev/vfd
+/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null
 
-   player=`cat /proc/stb/player/version`
-   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-   echo "init player $player"
+echo "Init embx (LOAD 6)"
+echo "Load 6" > /dev/vfd
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
+insmod $MODDIR/mme_host.ko transport0=shm
 
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
+echo "Init AVS (LOAD 5)"
+echo "Load 5" > /dev/vfd
+insmod $MODDIR/avs.ko type=avs_pio
+#insmod $MODDIR/avs.ko type=avs_none #HDMU value
+
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "Init player $player (LOAD 4)"
+echo "Load 4" > /dev/vfd
+
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+if [ $player -gt 131 ]; then
    insmod $MODDIR/stmvout.ko
    insmod $MODDIR/stmvbi.ko
-   insmod $MODDIR/pseudocard.ko
+fi
+insmod $MODDIR/pseudocard.ko
 
-   insmod $MODDIR/spark7162.ko UnionTunerType=t
-   insmod $MODDIR/pti.ko
+tunertype=`cat /etc/enigma2/settings | grep systemoptions.tunertype | cut -d "=" -f2`
+if [ ! $tunertype ]; then
+   tunertype='t'
+fi
+insmod $MODDIR/spark7162.ko UnionTunerType=$tunertype
+
+if [ $player -gt 131 ]; then
+   if [ -e $MODDIR/pti.ko ]; then
+#      if [ ! $?=='2' ]; then
+         pti_arg="waitMS=20 videoMem=4096"
+         echo "Full feature pti"
+#      else
+#         pti_arg=""
+#         echo "Simple pti"
+#     fi
+     insmod $MODDIR/pti.ko $pti_arg
+   fi
    insmod $MODDIR/stm_monitor.ko
    insmod $MODDIR/stmsysfs.ko
    insmod $MODDIR/stmdvb.ko
-   insmod $MODDIR/player2.ko
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
-   insmod $MODDIR/smartcard.ko
-   insmod $MODDIR/bpamem.ko
-
-   stfbcontrol a 0
-
-   echo "init lircd"
-   mkdir -p /var/run/lirc
-   /usr/bin/lircd
-
-#   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
-#   rm -f /dev/sparkid
-#   mknod /dev/sparkid c $major 0
-#   rm /f /dev/dvb/adapter0/ca1
-#   mknod /dev/dvb/adapter0/ca1 c 212 22
-
-   /bin/evremote2 spark 100 &
-
-   stfbcontrol a 255
-
-   # start automounter with umount timeout of 5 seconds
-   MKDIR -p /tmp/autofs
-   insmod $MODDIR/autofs4.ko
-   /usr/sbin/automount --ghost --timeout=5 /tmp/autofs file /etc/auto.usb
-
-#   echo "starting vsftpd"
-#   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   NFS=`grep -c nfs /proc/cmdline`
-   if [ "$NFS" -eq "1" ]; then
-      echo "Booting from nfs, don't set network"
-   else
-      if [ -e /etc/network/interfaces ]; then
-	 ip addr flush eth0
-	 /etc/init.d/networking stop
-	 DHCP=`grep -c dhcp /etc/network/interfaces`
-	 if [ "$DHCP" -eq "1" ]; then
-	    echo "Starting dhcp"
-            /etc/init.d/udhcpc start
-	 fi
-	 /etc/init.d/networking start
-      fi
-   fi
-
-   #timefix
-   date -s "200901011200"
-
-   # Set Display Time
-   (sleep 25;fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
-
-   #tuner workaround
-   export FE_OFFSET=1
-
-   echo "run" > /dev/vfd
-   echo "LOADING neutrino"
-
-   until false
-   do
-      echo "starting neutrino ->"
-      /usr/local/bin/neutrino
-      rtv=$?
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "SHUTDOWN"
-		   init 0;;
-		1) echo "1"
-		   echo "REBOOT"
-		   init 6;;
-		*) echo "*"
-		   echo "ERROR"
-		   init 6;;
-      esac
-   done
+else
+   insmod $MODDIR/pti.ko
+   insmod $MODDIR/stmdvb.ko
+#   /etc/init.d/stmdvb_check
+   insmod $MODDIR/stm_monitor.ko
 fi
 
+echo "Load 3" > /dev/vfd
+echo "Load 3"
+#insmod $MODDIR/player2.ko discardlateframe=0
+insmod $MODDIR/player2.ko
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+insmod $MODDIR/silencegen.ko
+
+insmod $MODDIR/smartcard.ko
+
+echo "Init HDMI-CEC"
+insmod $MODDIR/cec.ko activemode=1
+
+insmod $MODDIR/bpamem.ko
+mknod /dev/bpamem c 153 0
+
+showiframe -p /boot/bootlogo.mvi &
+stfbcontrol a 0
+
+echo "Init lircd (LOAD 2)"
+echo "Load 2" > /dev/vfd
+/usr/bin/lircd
+rm -rf /dev/rc
+mknod /dev/rc c 147 1 #VFD
+/bin/evremote2 10 120 &
+
+echo "Init smartcard cardreader"
+mknod /dev/sci0 c 169 0
+mknod /dev/sci1 c 169 1
+
+#major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
+#rm -f /dev/sparkid
+#mknod /dev/sparkid c $major 0
+
+stfbcontrol a 255
+
+wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "No WLAN"
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+if [ -e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+
+if [ -e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
+
+echo "Init FTP (LOAD 1)"
+echo "Load 1" > /dev/vfd
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+#mknod /dev/dvb/adapter0/frontend1 c 212 19  #SAT1
+#mknod /dev/dvb/adapter0/frontend2 c 212 35  #SAT2
+#mknod /dev/dvb/adapter0/frontend3 c 212 51  #T/C
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "Booting from nfs, don't set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "Starting DHCP on eth0"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start &
+   fi
+fi
+sleep 2
+
+# Start automount
+if [ -e /etc/init.d/automount ]; then
+   python /etc/init.d/automount &
+fi
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+# Try and synchronise time
+#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
+# if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
+if [ -e /sbin/ntpdate ]; then
+   echo "Set internet time"
+#   (/sbin/ntpdate pl.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
+   (/sbin/ntpdate de.pool.ntp.org; /bin/fp_control -sst) &
+else
+   if [ -e /usr/sbin/time.sh ]; then
+      echo "Use transponder time"
+      /usr/sbin/time.sh &
+   fi
+fi
+
+echo "Start Enigma2"
+echo "Start Enigma2" > /dev/vfd
+
+until false
+do
+   echo "Entering e2 main loop"
+   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+      showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+   fi
+   /usr/local/bin/enigma2
+   rtv=$?
+   echo "e2 ended <- RTV: " $rtv
+   /bin/fp_control -i 46 0
+   case "$rtv" in
+      0)  echo "0"
+          echo "E2 ERROR"
+          echo "E2 Error" > /dev/vfd
+          init 6;;
+      1)  echo "1"
+          echo "SHUTDOWN"
+          echo "Shutdown" > /dev/vfd
+          if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
+             showiframe -p /usr/local/share/enigma2/shutdown.mvi &
+          fi
+          init 0;;
+      2)  echo "2"
+          echo "REBOOT"
+          echo "Reboot" > /dev/vfd
+          init 6;;
+      3)  echo "3"
+          echo "E2 RESTART"
+          echo "Restart GUI" > /dev/vfd
+          echo "0" > /proc/progress
+          if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+             showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+          else
+             showiframe -p /boot/bootlogo.mvi &
+          fi;;
+      10) echo "10"
+          echo "SPARK RESTART"
+          echo "SPARK Restart" > /dev/vfd
+          insmod $MODDIR/i2s.ko
+          if [ ! -f /etc/fw_env.config ]; then
+             echo "fw_env.config not found - will create it"
+             echo '/dev/mtd7 0x000A0000 0x00020000 0x20000' > /etc/fw_env.config
+          fi
+          var=`fw_printenv | grep 'bootargs_spark='` ; fw_setenv bootargs ${var#*=}
+          var=`fw_printenv | grep 'bootcmd_spark='` ; fw_setenv bootcmd ${var#*=}
+          var=`fw_printenv | grep 'boot_system_spark='` ; fw_setenv boot_system ${var#*=}
+          var=`fw_printenv | grep 'userfs_base_spark='` ; fw_setenv userfs_base ${var#*=}
+          var=`fw_printenv | grep 'userfs_len_spark='` ; fw_setenv userfs_len ${var#*=}
+          var=`fw_printenv | grep 'kernel_base_spark='` ; fw_setenv kernel_base ${var#*=}
+          var=`fw_printenv | grep 'kernel_name_spark='` ; fw_setenv kernel_name ${var#*=}
+          var=`fw_printenv | grep 'userfs_name_spark='` ; fw_setenv userfs_name ${var#*=} 
+          var=`fw_printenv | grep 'loadu_userfs_spark='` ; fw_setenv loadu_userfs ${var#*=}
+          var=`fw_printenv | grep 'loadu_kernel_spark='` ; fw_setenv loadu_kernel ${var#*=}
+          var=`fw_printenv | grep 'kernel_len_spark='` ; fw_setenv kernel_len ${var#*=}
+          sync
+          init 6;;
+      *)  echo "*"
+          echo "ERROR"
+          echo "Error" > /dev/vfd
+          init 6;;
+   esac
+done 
+
 #never reached
-echo "REBOOT SPARK-7162" > /dev/vfd
-echo "REBOOT SPARK-7162"
-init 6
+echo "Reboot SPARK7162" > /dev/vfd
+echo "REBOOT SPARK7162"
+reboot -f
