Fixes for HS7420/HS7429

diff --git a/root/release/rcS_fortis_hdbox b/root/release/rcS_fortis_hdbox
--- a/root/release/rcS_fortis_hdbox
+++ b/root/release/rcS_fortis_hdbox
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-echo "[rcS] start"
+echo "Fortis FS9000/9200 Enigma2"
+
 MODDIR=/lib/modules
 
 if [ ! -e /dev/vfd ]; then
@@ -19,149 +20,145 @@ fi
 
 insmod $MODDIR/e2_proc.ko
 
-if [ ! -e /var/etc/.firstboot ]; then
+echo "Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
+echo "starting telnetd"
+/usr/sbin/telnetd -l /bin/autologin
 
-   echo "starting telnetd"
-   /usr/sbin/telnetd -l /bin/autologin
-
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-stx7109c3.ko
-   insmod $MODDIR/stmfb.ko display0=720x576-32@50:15m:pal:yuv:yuv
+echo "init stmfb"
+insmod $MODDIR/stmcore-display-stx7109c3.ko
+insmod $MODDIR/stmfb.ko display0=720x576-32@50:15m:pal:yuv:yuv
   
-   echo "STB7100-VIDEO"
-   /bin/ustslave /dev/st231-0 /boot/video.elf
-   echo "STB7100-AUDIO"
-   /bin/ustslave /dev/st231-1 /boot/audio.elf
+echo "STB7100-VIDEO"
+/bin/ustslave /dev/st231-0 /boot/video.elf
+echo "STB7100-AUDIO"
+/bin/ustslave /dev/st231-1 /boot/audio.elf
 
-   echo "LOADING MODULES"
-   echo "LOADING MODULES" >/dev/vfd
+echo "LOADING MODULES"
+echo "LOADING MODULES" >/dev/vfd
 
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
-   insmod $MODDIR/mme_host.ko transport0=shm
+echo "init embx"
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
+insmod $MODDIR/mme_host.ko transport0=shm
 
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=stv6412
+echo "init AVS"
+insmod $MODDIR/avs.ko type=stv6412
 
-   player=`cat /proc/stb/player/version`
-   if [ $player=='player179' ]; then
-      echo "init player 179"
-   elif [ $player=='player191' ]; then
-      echo "init player 191"
-   else
-      echo "init player 131"
-   fi
+player=`cat /proc/stb/player/version`
+if [ $player=='player179' ]; then
+   echo "init player 179"
+elif [ $player=='player191' ]; then
+   echo "init player 191"
+else
+   echo "init player 131"
+fi
 
-   echo "init player"
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   insmod $MODDIR/pseudocard.ko
+echo "init player"
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/pseudocard.ko
 
-   insmod $MODDIR/stv090x.ko
-   insmod $MODDIR/starci.ko
+insmod $MODDIR/stv090x.ko
+insmod $MODDIR/starci.ko
 
-   if [ $player=='player179' ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   elif [ $player=='player191' ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   else
+if [ $player=='player179' ]; then
+   # Full feature pti
+   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+   if [ $?=='2' ]; then
+      # Simple pti
       insmod $MODDIR/pti.ko
-      insmod $MODDIR/stmdvb.ko
-      insmod $MODDIR/stm_monitor.ko
    fi
+   insmod $MODDIR/stm_monitor.ko
+   insmod $MODDIR/stmsysfs.ko
+   insmod $MODDIR/stmdvb.ko
+elif [ $player=='player191' ]; then
+   # Full feature pti
+   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+   if [ $?=='2' ]; then
+      # Simple pti
+      insmod $MODDIR/pti.ko
+   fi
+   insmod $MODDIR/stm_monitor.ko
+   insmod $MODDIR/stmsysfs.ko
+   insmod $MODDIR/stmdvb.ko
+else
+   insmod $MODDIR/pti.ko
+   insmod $MODDIR/stmdvb.ko
+   insmod $MODDIR/stm_monitor.ko
+fi
 
-   insmod $MODDIR/player2.ko noaudiosync=1; discardlateframe=0; useoldaudiofw=1 ;
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
+insmod $MODDIR/player2.ko noaudiosync=1; discardlateframe=0; useoldaudiofw=1 ;
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
 
-  # insmod $MODDIR/cifs.ko
+if [-e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
 
-   echo "init frontpanel"
-   insmod $MODDIR/boxtype.ko
-   insmod $MODDIR/simu_button.ko
+if [-e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+
+echo "init frontpanel"
+insmod $MODDIR/boxtype.ko
+insmod $MODDIR/simu_button.ko
 
    mknod /dev/rc c 147 1
 
-   #params:
-   #period
-   #delay
-   /bin/evremote2 10 140 &
+/bin/evremote2 10 140 &
 
-   echo "init cardreader"
-   mknod /dev/sci0 c 253 0
-   mknod /dev/sci1 c 253 1
-#	insmod $MODDIR/sci-ng.ko
+echo "init cardreader"
+mknod /dev/sci0 c 253 0
+mknod /dev/sci1 c 253 1
+#insmod $MODDIR/sci-ng.ko
 
-   #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
-   #mount /dev/sr0 /media/dvd
-   #fix this later if we got to manage a marusys raw device driver
+#DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
+#mount /dev/sr0 /media/dvd
+#fix this later if we got to manage a marusys raw device driver
 
-   /etc/init.d/portmap start
-   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
 
-   #timefix e2
-   date -s "200901011200"
+#timefix e2
+date -s "201601011200"
 
 #   stfbcontrol a 255
 
-   echo "LOADING e2" > /dev/vfd
-   echo "LOADING e2"
+echo "LOADING e2" > /dev/vfd
+echo "LOADING e2"
 
-   until false
-   do
-      echo "starting e2->"
-      /usr/local/bin/enigma2
-      rtv=$?
-      echo "e2 ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "E2 ERROR"
-      	   init 6;;
-		1) echo "1"
-		   echo "SHUTDOWN"
-		   init 0;;
-		2) echo "2"
-		   echo "REBOOT"
-		   init 6;;
-		3) echo "3"
-		   echo "E2 RESTART"
-		   echo "0" > /proc/progress
-		   showiframe -p /var/boot/bootlogo.mvi &;;
-		*) echo "*"
-		   echo "ERROR"
-           init 6;;
-      esac
-   done
-fi
+until false
+do
+   echo "starting e2->"
+   /usr/local/bin/enigma2
+   rtv=$?
+   echo "e2 ended <- RTV: " $rtv
+   case "$rtv" in
+      0) echo "E2 ERROR"
+         init 6;;
+      1) echo "SHUTDOWN"
+         init 0;;
+      2) echo "REBOOT"
+         init 6;;
+      3) echo "E2 RESTART"
+         echo "0" > /proc/progress
+         showiframe -p /var/boot/bootlogo.mvi &;;
+      *) echo "ERROR"
+         init 6;;
+   esac
+done
 
 #never reached
 echo "REBOOT HDBOX" > /dev/vfd
 echo "REBOOT HDBOX"
 reboot
+
